import { contentDigest } from "@earendil-works/pi-ai";
import { describe, expect, it } from "vitest";
import { createEditToolDefinition } from "../src/core/tools/edit.ts";

/**
 * The edit tool's guards.
 *
 * The property is that **a rejected edit leaves the file byte-identical**. Both
 * guards run before any write, so a refusal is observable as "the file did not
 * change" rather than as a partial application — which is the failure mode that
 * makes a guard worse than no guard.
 */

const makeTool = (
	content: string,
	options: { readSetting?: (key: string) => unknown; seenDigests?: Map<string, string> } = {},
) => {
	let written: string | undefined;
	const bytes = Buffer.from(content, "utf8");
	const tool = createEditToolDefinition("C:/repo", {
		...options,
		operations: {
			readFile: async () => bytes,
			writeFile: async (_path, next) => {
				written = next;
			},
			access: async () => {},
		},
	});
	return {
		tool,
		written: () => written,
	};
};

const apply = (tool: ReturnType<typeof makeTool>["tool"]) =>
	// The edit tool declares an ExtensionContext slot beyond the four-argument tool
	// contract, so the call passes all five.
	tool.execute("call-1", { path: "C:\\repo\\a.ts", edits: [{ oldText: "42", newText: "43" }] }, undefined, undefined, {
		cwd: "C:/repo",
	} as never);

describe("a stale edit is refused", () => {
	it("refuses when the file changed since the model read it", async () => {
		// A formatter ran between the read and the edit. Nothing else would catch
		// this: the oldText still matches, the write succeeds, and the result is a
		// file nobody intended.
		const current = "export const answer = 42;\n// a formatter ran\n";
		const { tool, written } = makeTool(current, {
			seenDigests: new Map([["C:\\repo\\a.ts", contentDigest("export const answer = 42;\n")]]),
		});
		await expect(apply(tool)).rejects.toThrow(/has changed since you read it/);
		expect(written()).toBeUndefined();
	});

	it("allows the same edit against unchanged content", async () => {
		const current = "export const answer = 42;\n";
		const { tool, written } = makeTool(current, {
			seenDigests: new Map([["C:\\repo\\a.ts", contentDigest(current)]]),
		});
		await apply(tool);
		expect(written()).toContain("43");
	});

	it("allows an edit with no recorded read", async () => {
		// A model creating a file has read nothing, and that is legitimate.
		const { tool, written } = makeTool("export const answer = 42;\n");
		await apply(tool);
		expect(written()).toContain("43");
	});
});

describe("an auto-generated file is refused by default", () => {
	it("refuses and names the generator", async () => {
		const { tool, written } = makeTool("// Code generated by protoc. DO NOT EDIT.\nconst x = 42;\n");
		await expect(apply(tool)).rejects.toThrow(/auto-generated/);
		// Regenerating discards the edit, so writing first would be worse than
		// refusing: the write would appear to succeed and then be reverted.
		expect(written()).toBeUndefined();
	});

	it("allows one when the user turns the guard off", async () => {
		const { tool, written } = makeTool("// Code generated by protoc. DO NOT EDIT.\nconst x = 42;\n", {
			readSetting: (key) => (key === "edit.blockAutoGenerated" ? false : undefined),
		});
		await apply(tool);
		expect(written()).toContain("43");
	});

	it("leaves an ordinary file alone", async () => {
		const { tool, written } = makeTool("const x = 42;\n");
		await apply(tool);
		expect(written()).toContain("43");
	});
});
