import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { contentDigest } from "@earendil-works/pi-ai";
import { getModel } from "@earendil-works/pi-ai/compat";
import { describe, expect, it } from "vitest";
import { createSeenLineSource, createTag, SeenLineIndex } from "../src/core/edit/seen-lines.ts";
import { DefaultResourceLoader } from "../src/core/resource-loader.ts";
import { createAgentSession } from "../src/core/sdk.ts";
import { SessionManager } from "../src/core/session-manager.ts";
import { SettingsManager } from "../src/core/settings-manager.ts";
import { createEditToolDefinition, type SeenLineSource } from "../src/core/tools/edit.ts";
import { createReadToolDefinition, type ReadOperations } from "../src/core/tools/read.ts";

/**
 * The edit tool's guards, driven through the path the product uses.
 *
 * The property is that **a rejected edit leaves the file byte-identical**. Every
 * guard runs before any write, so a refusal is observable as "the file did not
 * change" rather than as a partial application — which is the failure mode that
 * makes a guard worse than no guard.
 *
 * ## Why this file replaced a map-supplying test
 *
 * The previous version handed the tool a `seenDigests` map it built itself, which
 * proved the *comparison* and nothing about the *feed*. The product never built
 * that map, so the test passed against a guard that governed nothing. Here the
 * provenance is produced by running the real read tool and consumed by the real
 * edit tool through the same adapter the session supplies, so a break anywhere in
 * read -> record -> check is a failure here.
 *
 * ## The two digest schemes, and why both are asserted
 *
 * `createTag` is 32-bit FNV over path+text; `contentDigest` is a wider FNV over
 * content alone. They are not interchangeable. Feeding a tag where a digest is
 * expected makes every comparison mismatch, i.e. **every edit refused** — the
 * guard's worst failure mode, reached by a wiring mistake that type-checks. The
 * test therefore pins the exact bytes in each map.
 */

const REPO = "C:/repo";
const FILE = "C:\\repo\\a.ts";

/** A one-file session, wired the way `AgentSession._buildRuntime` wires it. */
function makeSession(initialContent: string, options: { enforce?: boolean; blockAutoGenerated?: boolean } = {}) {
	let onDisk = initialContent;
	const index = new SeenLineIndex();
	const seenDigests = new Map<string, string>();

	const readOperations: ReadOperations = {
		readFile: async () => Buffer.from(onDisk, "utf8"),
		access: async () => {},
		detectImageMimeType: async () => undefined,
	};

	// The adapter the session owns: it records what a read displayed, and answers
	// the edit tool's question from the same index.
	const onRead = (observed: {
		absolutePath: string;
		text: string;
		firstLine: number;
		lastLine: number;
		summarized: boolean;
	}): void => {
		// A summarized read displayed no line, so the range is empty. Recording the
		// file's full extent here would claim provenance the model never had.
		const seenLines =
			observed.summarized || observed.lastLine < observed.firstLine
				? []
				: Array.from(
						{ length: observed.lastLine - observed.firstLine + 1 },
						(_, index) => observed.firstLine + index,
					);
		index.recordSnapshot(observed.absolutePath, observed.text, seenLines);
		// `contentDigest`, never `createTag`. A 32-bit tag here would make every
		// subsequent edit look stale.
		seenDigests.set(observed.absolutePath, contentDigest(observed.text));
	};

	// The production adapter, not a hand-rolled one. A stub here would let the
	// "untracked path has no opinion" rule live only in the test, which is the
	// shape of bug where the guard is real in the harness and absent in the
	// product.
	const enforce = (): boolean => options.enforce !== false;
	const seenLines: SeenLineSource = createSeenLineSource(index, enforce);
	const originalRecordWrite = seenLines.recordWrite;
	seenLines.recordWrite = (absolutePath, text) => {
		originalRecordWrite(absolutePath, text);
		// `contentDigest`, never `createTag`. A 32-bit tag here would make every
		// subsequent edit look stale, which is the guard's worst failure mode and
		// type-checks cleanly, so it is asserted here rather than trusted.
		seenDigests.set(absolutePath, contentDigest(text));
	};

	const readTool = createReadToolDefinition(REPO, { operations: readOperations, onRead });
	const editTool = createEditToolDefinition(REPO, {
		operations: {
			readFile: async () => Buffer.from(onDisk, "utf8"),
			writeFile: async (_path, next) => {
				onDisk = next;
			},
			access: async () => {},
		},
		readSetting: (key) => (key === "edit.blockAutoGenerated" ? options.blockAutoGenerated !== false : undefined),
		seenDigests,
		seenLines,
	});

	return {
		read: (input: { path: string; offset?: number; limit?: number }) =>
			readTool.execute("read-1", input, undefined, undefined, { cwd: REPO } as never),
		edit: (edits: { oldText: string; newText: string }[]) =>
			editTool.execute("edit-1", { path: FILE, edits }, undefined, undefined, { cwd: REPO } as never),
		content: () => onDisk,
		index,
		seenDigests,
	};
}

describe("a stale edit is refused", () => {
	it("refuses when the file changed since the model read it", async () => {
		// A formatter ran between the read and the edit. Nothing else catches this:
		// the oldText still matches, the write succeeds, and the result is a file
		// nobody intended.
		const session = makeSession("export const answer = 42;\n// a formatter ran\n");
		await session.read({ path: FILE });
		// The digest the session holds is the one the model reasoned about, and the
		// file has since moved on: a read of the pre-formatter content.
		session.seenDigests.set(FILE, contentDigest("export const answer = 42;\n"));

		await expect(session.edit([{ oldText: "42", newText: "43" }])).rejects.toThrow(/has changed since you read it/);
		expect(session.content()).toBe("export const answer = 42;\n// a formatter ran\n");
	});

	it("allows the same edit against unchanged content", async () => {
		const session = makeSession("export const answer = 42;\n");
		await session.read({ path: FILE });
		await session.edit([{ oldText: "42", newText: "43" }]);
		expect(session.content()).toContain("43");
	});

	it("allows an edit with no recorded read", async () => {
		// A model creating a file has read nothing, and that is legitimate.
		const session = makeSession("export const answer = 42;\n");
		await session.edit([{ oldText: "42", newText: "43" }]);
		expect(session.content()).toContain("43");
	});
});

describe("an edit anchored on a line no read displayed is refused", () => {
	it("refuses an edit outside a paged read", async () => {
		// The failure the module header describes: the model read lines 1-2 of a
		// 4-line file and edits line 4, which it has never seen.
		const session = makeSession("a\nb\nc\nd\n");
		await session.read({ path: FILE, offset: 1, limit: 2 });

		await expect(session.edit([{ oldText: "d", newText: "D" }])).rejects.toThrow(/no read displayed in full/);
		expect(session.content()).toBe("a\nb\nc\nd\n");
	});

	it("allows an edit inside the paged range", async () => {
		const session = makeSession("a\nb\nc\nd\n");
		await session.read({ path: FILE, offset: 1, limit: 2 });
		await session.edit([{ oldText: "b", newText: "B" }]);
		expect(session.content()).toBe("a\nB\nc\nd\n");
	});

	it("refuses a second page that was never read", async () => {
		const session = makeSession("a\nb\nc\nd\ne\n");
		await session.read({ path: FILE, offset: 1, limit: 2 });
		await session.read({ path: FILE, offset: 3, limit: 2 });
		await expect(session.edit([{ oldText: "e", newText: "E" }])).rejects.toThrow(/no read displayed in full/);
		expect(session.content()).toBe("a\nb\nc\nd\ne\n");
	});

	it("allows the guard to be turned off by the user", async () => {
		const session = makeSession("a\nb\nc\nd\n", { enforce: false });
		await session.read({ path: FILE, offset: 1, limit: 2 });
		await session.edit([{ oldText: "d", newText: "D" }]);
		expect(session.content()).toBe("a\nb\nc\nD\n");
	});
});

describe("a second edit in a file is not blocked by the first", () => {
	// This is the false positive that decides whether the guard is shippable. A
	// model that cannot edit retries, and a model that retries a refused edit
	// spends its budget on something else, so a guard that breaks the *second*
	// edit is worse than no guard at all.
	it("allows an edit after an earlier edit in the same file", async () => {
		const session = makeSession("a\nb\nc\n");
		await session.read({ path: FILE });
		await session.edit([{ oldText: "a", newText: "A" }]);
		await session.edit([{ oldText: "c", newText: "C" }]);
		expect(session.content()).toBe("A\nb\nC\n");
	});

	it("allows an edit the file's own earlier write produced", async () => {
		// The second edit anchors on text the first write created. Nothing displayed
		// that text, but the model composed it, so it is known.
		const session = makeSession("a\nb\nc\n");
		await session.read({ path: FILE });
		await session.edit([{ oldText: "a", newText: "one\ntwo" }]);
		await session.edit([{ oldText: "two", newText: "TWO" }]);
		expect(session.content()).toBe("one\nTWO\nb\nc\n");
	});
});

describe("an auto-generated file is refused by default", () => {
	it("refuses and names the generator", async () => {
		const session = makeSession("// Code generated by protoc. DO NOT EDIT.\nconst x = 42;\n");
		await expect(session.edit([{ oldText: "42", newText: "43" }])).rejects.toThrow(/auto-generated/);
		// Regenerating discards the edit, so writing first would be worse than
		// refusing: the write would appear to succeed and then be reverted.
		expect(session.content()).not.toContain("43");
	});

	it("allows one when the user turns the guard off", async () => {
		const session = makeSession("// Code generated by protoc. DO NOT EDIT.\nconst x = 42;\n", {
			blockAutoGenerated: false,
		});
		await session.edit([{ oldText: "42", newText: "43" }]);
		expect(session.content()).toContain("43");
	});

	it("leaves an ordinary file alone", async () => {
		const session = makeSession("const x = 42;\n");
		await session.edit([{ oldText: "42", newText: "43" }]);
		expect(session.content()).toContain("43");
	});
});

describe("the recorded snapshot is keyed by content, not by path", () => {
	it("treats a changed file as having no seen lines at all", async () => {
		// The soundness property the whole design rests on: if seen-ness were keyed
		// per path, any change would leave stale lines marked seen, and the guard
		// would wave through precisely the edit it exists to stop.
		const session = makeSession("a\nb\nc\nd\n");
		await session.read({ path: FILE, offset: 1, limit: 2 });
		const decision = session.index.check({
			absolutePath: FILE,
			tag: createTag(FILE, "a\nb\nc\nCHANGED\n"),
			editLines: [1],
			enforce: true,
		});
		expect(decision.allowed).toBe(false);
		expect(decision.reason).toMatch(/no read of this content is recorded/);
	});
});

/**
 * The same guard, through a real session.
 *
 * The tests above wire the tools by hand, which proves the pieces fit. This one
 * builds the session the product builds and asks it to edit, because the wiring
 * that was actually missing lived in `_buildRuntime`: the tools were constructed
 * with no `edit:` key at all, so `seenDigests` and `seenLines` were `undefined`
 * and `checkEditFreshness` returned `{ok:true}` on its first line for every edit
 * in the product. A test that supplies the options itself cannot see that — which
 * is exactly why the earlier version of this file was replaced rather than kept.
 */
describe("a real session enforces the guard it claims to", () => {
	const buildSession = async (dir: string, settings: Record<string, unknown>) => {
		const cwd = mkdtempSync(join(tmpdir(), dir));
		const agentDir = join(cwd, "agent");
		writeFileSync(join(cwd, "sample.txt"), "a\nb\nc\nd\n");
		const settingsManager = SettingsManager.inMemory(settings);
		const resourceLoader = new DefaultResourceLoader({
			cwd,
			agentDir,
			settingsManager,
			noExtensions: true,
			noSkills: true,
			noPromptTemplates: true,
			noThemes: true,
		});
		await resourceLoader.reload();
		const { session } = await createAgentSession({
			cwd,
			agentDir,
			model: getModel("anthropic", "claude-sonnet-4-5"),
			settingsManager,
			sessionManager: SessionManager.inMemory(cwd),
			resourceLoader,
		});
		return { cwd, session, target: join(cwd, "sample.txt") };
	};

	it("refuses an edit on a line the session never read", async () => {
		const { cwd, session, target } = await buildSession("pi-seen-lines-", {});
		try {
			const read = session.getToolDefinition("read");
			const edit = session.getToolDefinition("edit");
			expect(read, "the session must expose read").toBeDefined();
			expect(edit, "the session must expose edit").toBeDefined();

			await read!.execute("r1", { path: "sample.txt", offset: 1, limit: 2 }, undefined, undefined, {
				cwd,
			} as never);

			await expect(
				edit!.execute("e1", { path: "sample.txt", edits: [{ oldText: "d", newText: "D" }] }, undefined, undefined, {
					cwd,
				} as never),
			).rejects.toThrow(/no read displayed in full/);
			expect(readFileSync(target, "utf8"), "a refused edit leaves the file byte-identical").toBe("a\nb\nc\nd\n");

			// An edit inside the range the session did read is allowed, and a second
			// edit afterwards is not blocked by the first — the majority case.
			await edit!.execute(
				"e2",
				{ path: "sample.txt", edits: [{ oldText: "b", newText: "B" }] },
				undefined,
				undefined,
				{ cwd } as never,
			);
			expect(readFileSync(target, "utf8")).toBe("a\nB\nc\nd\n");
		} finally {
			await session.dispose();
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("lets a user turn the guard off through the registry", async () => {
		// Configured the way a user configures it — a nested object parsed by the
		// registry — rather than by handing the tool a boolean, so the test proves
		// the key is writable as well as read. A guard that cannot be disabled is a
		// guard that will be reported as a bug and worked around.
		const { cwd, session, target } = await buildSession("pi-seen-lines-off-", {
			edit: { enforceSeenLines: false },
		});
		try {
			const read = session.getToolDefinition("read")!;
			const edit = session.getToolDefinition("edit")!;
			await read.execute("r1", { path: "sample.txt", offset: 1, limit: 2 }, undefined, undefined, {
				cwd,
			} as never);
			await edit.execute(
				"e1",
				{ path: "sample.txt", edits: [{ oldText: "d", newText: "D" }] },
				undefined,
				undefined,
				{ cwd } as never,
			);
			expect(readFileSync(target, "utf8")).toBe("a\nb\nc\nD\n");
		} finally {
			await session.dispose();
			rmSync(cwd, { recursive: true, force: true });
		}
	});
});
