/**
 * Edit guards: what an edit may be applied to, and what it may change.
 *
 * ## Staleness is a correctness problem, not a style one
 *
 * A model read a file, thought about it, and then edits it. If the file changed
 * in between — a formatter, a hook, another agent, the user's editor — the
 * model is writing against a version that no longer exists. The `oldText` may
 * still match, and the edit lands, and the result is a file nobody intended.
 *
 * That is silent. Nothing errors. The write succeeds. So the guard has to be
 * explicit, and the failure has to name the drift rather than reporting a
 * generic "not found".
 *
 * ## A digest, not the content
 *
 * The model supplies the digest of the content it read, and the guard compares
 * it against the file as it is now. Storing the text itself would double the
 * memory a session holds for a file it has already read, and comparing text
 * would mean an O(n) comparison on every edit. A short digest is enough: a
 * mismatch is the signal, not the diagnosis.
 *
 * ## The guard is per-call, not per-session
 *
 * OMP's `enforceSeenLines` is a session-wide policy consulted by a native
 * matcher. This is deliberately weaker and says so: it catches the case where
 * the file changed between the read and the edit, and it does not try to prove
 * that every line the model referenced was one it actually saw. That stronger
 * claim needs the session's read history, which the tool does not have.
 */

/** A model-supplied digest of the content it read. */
export interface SeenDigest {
	readonly path: string;
	readonly digest: string;
}

/** A short, cheap content digest. */
export function contentDigest(content: string): string {
	// A full SHA-256 would be correct and wasteful; the guard only needs a value
	// that changes when the content does, and a 53-bit FNV-1a is enough for that.
	let hash = 0xcbf29ce484222325n;
	for (let index = 0; index < content.length; index++) {
		hash ^= BigInt(content.charCodeAt(index));
		// FNV prime 1099511628211, kept in the 64-bit domain.
		hash = (hash * 0x100000001b3n) & 0xffffffffffffffffn;
	}
	return hash.toString(16).padStart(16, "0");
}

/** What the guard decided about one edit. */
export type StalenessDecision =
	| { readonly ok: true }
	| { readonly ok: false; readonly reason: "no-digest" | "stale"; readonly detail: string };

/**
 * Decides whether an edit may proceed against the file as it is now.
 *
 * `seen` is what the model said it read. Absent is not a failure: a model that
 * edits without reading is common and legitimate when the edit is an insertion
 * into a file it is creating. The guard is here for the case where a digest
 * *was* supplied and no longer matches, because that is an unambiguous signal.
 */
export function checkEditFreshness(input: {
	readonly path: string;
	readonly currentContent: string;
	readonly seenDigest: string | undefined;
}): StalenessDecision {
	if (input.seenDigest === undefined) {
		return { ok: true };
	}
	const actual = contentDigest(input.currentContent);
	if (actual === input.seenDigest) return { ok: true };
	// Named precisely: "text not found" would send the model looking for a typo in
	// its own arguments, when the actual problem is that the file moved on.
	return {
		ok: false,
		reason: "stale",
		detail:
			`${input.path} has changed since you read it (your digest ${input.seenDigest}, current ${actual}). ` +
			`Re-read the file and re-apply the edit against the current content.`,
	};
}

/** Whether a set of auto-generated markers should block an edit. */
export function isAutoGenerated(content: string): boolean {
	// The conventional generated-file header. Deliberately narrow: a broad marker
	// would block edits to ordinary files that merely mention being generated.
	return /^\s*(?:\/\/|#|\/\*)\s*(?:@generated|Code generated by|This file is (?:auto-)?generated)/im.test(content);
}

/**
 * Decides whether an edit to a file is allowed at all.
 *
 * Blocking a generated file by default is right because regenerating it discards
 * the edit, so the write would appear to succeed and then be silently reverted by
 * the next build. The user can still edit one deliberately.
 */
export function checkEditAllowed(input: {
	readonly blockAutoGenerated: boolean;
	readonly currentContent: string;
	readonly path: string;
}): { ok: true } | { ok: false; reason: "auto-generated"; detail: string } {
	if (!input.blockAutoGenerated || !isAutoGenerated(input.currentContent)) return { ok: true };
	return {
		ok: false,
		reason: "auto-generated",
		detail:
			`${input.path} looks auto-generated. Editing it is overwritten by the next build; ` +
			`change the generator or its inputs instead, or set edit.blockAutoGenerated=false.`,
	};
}
