import { describe, expect, it } from "vitest";
import { checkEditAllowed, checkEditFreshness, contentDigest, isAutoGenerated } from "../src/utils/edit-guards.ts";

/**
 * Edit guards.
 *
 * The property is that a **stale edit is refused and named**. A model read a
 * file, a formatter changed it, and the `oldText` still matches — the write
 * succeeds, nothing errors, and the result is a file nobody intended. So the
 * failure message has to say the file moved, because "text not found" would send
 * the model hunting for a typo in its own arguments.
 */

const CONTENT = "export const answer = 42;\n";

describe("the digest", () => {
	it("is stable for the same content", () => {
		expect(contentDigest(CONTENT)).toBe(contentDigest(CONTENT));
	});

	it("changes when the content changes", () => {
		// The whole guard rests on this: a mismatch has to be detectable.
		expect(contentDigest(CONTENT)).not.toBe(contentDigest(`${CONTENT}// edited\n`));
	});

	it("separates a one-character change", () => {
		expect(contentDigest("a")).not.toBe(contentDigest("b"));
	});
});

describe("freshness", () => {
	it("allows an edit against content the model actually read", () => {
		const check = checkEditFreshness({
			path: "src/a.ts",
			currentContent: CONTENT,
			seenDigest: contentDigest(CONTENT),
		});
		expect(check.ok).toBe(true);
	});

	it("refuses an edit against content that has since changed", () => {
		const check = checkEditFreshness({
			path: "src/a.ts",
			currentContent: `${CONTENT}// a formatter ran\n`,
			seenDigest: contentDigest(CONTENT),
		});
		expect(check.ok).toBe(false);
		if (check.ok) return;
		expect(check.reason).toBe("stale");
	});

	it("names the file and both digests", () => {
		// The model has to be able to act on this: re-read and re-apply.
		const seen = contentDigest(CONTENT);
		const check = checkEditFreshness({
			path: "src/a.ts",
			currentContent: "different",
			seenDigest: seen,
		});
		if (check.ok) return;
		expect(check.detail).toContain("src/a.ts");
		expect(check.detail).toContain(seen);
		expect(check.detail).toContain("Re-read");
	});

	it("does not claim the text was not found", () => {
		// That wording would send the model looking for a typo in its arguments.
		const check = checkEditFreshness({ path: "a.ts", currentContent: "x", seenDigest: contentDigest(CONTENT) });
		if (check.ok) return;
		expect(check.detail).not.toMatch(/not found/i);
	});

	it("allows an edit with no digest at all", () => {
		// A model creating a file has read nothing and that is legitimate.
		expect(checkEditFreshness({ path: "src/new.ts", currentContent: CONTENT, seenDigest: undefined }).ok).toBe(true);
	});
});

describe("auto-generated files", () => {
	it("recognises the conventional markers", () => {
		expect(isAutoGenerated("// Code generated by protoc. DO NOT EDIT.\npackage x")).toBe(true);
		expect(isAutoGenerated("# @generated by a tool\nfoo")).toBe(true);
		expect(isAutoGenerated("/* eslint-disable */\n")).toBe(false);
	});

	it("does not match a file that merely mentions being generated", () => {
		// A broad marker would block edits to ordinary files.
		expect(isAutoGenerated("const x = 'this file is generated';\n")).toBe(false);
		expect(isAutoGenerated("export const answer = 42;\n")).toBe(false);
	});

	it("blocks an edit by default", () => {
		// Regenerating discards the edit, so the write would appear to succeed and
		// then be silently reverted by the next build.
		const check = checkEditAllowed({
			blockAutoGenerated: true,
			currentContent: "// Code generated by protoc.\npackage x",
			path: "gen/a.go",
		});
		expect(check.ok).toBe(false);
	});

	it("allows one when the user turns the guard off", () => {
		expect(
			checkEditAllowed({
				blockAutoGenerated: false,
				currentContent: "// Code generated by protoc.\npackage x",
				path: "gen/a.go",
			}).ok,
		).toBe(true);
	});

	it("points at the generator rather than at the file", () => {
		const check = checkEditAllowed({
			blockAutoGenerated: true,
			currentContent: "// Code generated by protoc.\npackage x",
			path: "gen/a.go",
		});
		if (check.ok) return;
		expect(check.detail).toContain("generator");
		expect(check.detail).toContain("edit.blockAutoGenerated");
	});

	it("leaves an ordinary file alone", () => {
		expect(checkEditAllowed({ blockAutoGenerated: true, currentContent: CONTENT, path: "src/a.ts" }).ok).toBe(true);
	});
});
